### ISSUE TITLE
Differentiate supported_features in cover by device_id 

### ISSUE THREAD

**Issue by zpieslak** [zpieslak/mobilus-client-home-assistant#12]
[Reference comment](https://github.com/zpieslak/mobilus-client-home-assistant/issues/9#issuecomment-2449634902)

Some devices does not support set_position and it shuold be disabled for them

**Comment by zpieslak** [comment]
@Jasbi90 Do I understand correclty that for some devices percentage is not allowed (COSMO and CMR) and [supprted_features](https://github.com/zpieslak/mobilus-client-home-assistant/blob/main/custom_components/mobilus/cover.py#L89-L95) sould only show? 

```
CoverEntityFeature.OPEN
 | CoverEntityFeature.CLOSE
 | CoverEntityFeature.STOP
```

**Comment by Jasbi90** [comment]
Yes, Cosmo and CMR do not support setting a percentage. Only up, down, and stop are possible.

**Comment by danielkedzior** [comment]
Cosmo or Cosmo 2way? I have CMR and Cosmo 2way, and CMR doesn't support percentage, But cosmo support it.

**Comment by Jasbi90** [comment]
Which Cosmo Do you have?
https://mobilus.pl/mobilus-products/mobilus-tubular-motors/silowniki-mobilus-m35/
The ERS with Senso 4.0? 

My Mobilus MR dont Support percent.

**Comment by danielkedzior** [comment]
sorry but I'm not sure, I will check. As I remember, probably with senso 2.0. They are from 2019/2020 year

**Comment by zpieslak** [comment]
Hey,

I added better support for modules that does not support position (thanks @Jasbi90 for pointing in COSMO javascript file). If possible please let me know if that works for you (if slider is hidden for your CMR module). The changes are in master. Thanks!

**Comment by Jasbi90** [comment]
Hey,

I updated to the latest version, and now the slider is hidden. The up, stop, and down functions are working, as well as the position feedback from the shutter (device 2 / Mobilus).

Thank you for implementing this feature!

**Comment by zpieslak** [comment]
No problem :) Thank you @Jasbi90 for your help.

**Comment by danielkedzior** [comment]
I confirm, after the update shutters without the percentage position only display up/down and stop, and those with the percentage display the slider for the percentage setting. Thank you
