### ISSUE TITLE
Controlling shutter tilt for Mobilus C-ZR

### ISSUE THREAD

**Issue by zbyhoo** [zpieslak/mobilus-client-home-assistant#22]
Thanks for great library and integration.
The following is not an issue, more like a feature request.

Currently mobilus_client is able to control shutter opening, closing and stopping. Everything works within Home Assistant.

Mobilus C-ZR connected to Mobilus Cosmo GTW is also able to controll shutter tilt. In GTW I'm able to set each shutter tilt using slider (from 0% - lamellas closed, to 100% - lamellas opened).

With help @zpieslak I was able to get devices list and set shutter lamellas tilt using mobilus_client library in the following way:

`python -m mobilus_client --host=MOBIULS_IP --login=MOBILUS_USER --password=MOBILUS_PASSWORD call_events:device_id=4,value=DOWN:60$`

This command moved shutter to closed position and opened lamellas to 60%.
The following values were properly handled:
`value=DOWN`
`value=STOP`
`value=UP`
`value=DOWN:80$`

The following ones, are not correclty handled:
`value=50%:80$`
This one was not changing shutter position, but only opening lamellas to 50%.

Maybe this controller doesn't have position setter, it's also not preset in Mobilus Cosmo GTW. There are only options:
- button up
- button stop
- button down
- slider for tilt

**Comment by zpieslak** [comment]
Hi @zbyhoo,

Thank you for your detailed report. Just a few more questions:

- what happens when you run call_events_request with `value=35%` or `value=50%` ?
- when you run `value=50%:80$` the tilt changes to 80%, but shutter itself does not move?

It looks like the tilt support can be added via tilt feature [Reference](https://github.com/home-assistant/core/blob/0199418ba9d2c86c69c4a9e025b6d45eafa6b00d/homeassistant/components/cover/__init__.py#L463-L467). So it should not be a problem to implement it. I will try to do it in spare moment.

**Comment by zbyhoo** [comment]
> what happens when you run call_events_request with value=35% or value=50% ?
It changes tilt to specified pct value.

> when you run value=50%:80$ the tilt changes to 80%, but shutter itself does not move?
This also changes tilt to value 50%, second parameter is neglected.

Additional tests:
value=50  --> nothing happens
value=50% --> changes tilt
value=50$ --> changes tilt
value=20%:80$ --> changes tilt to 20%, no position change
value=DOWN:20$ --> position change and when shutter is closed, it tilts to 20%
value=UP:10$ --> nothing happens
value=STOP:30$ --> when currently is running (opening or closing) it stops and changes tilt to 30%, when idle, nothing happens

**Comment by zpieslak** [comment]
Thanks @zbyhoo that should be enough. Although (as you mentioned in our discussion) it looks like the shutter itself does not support percentage position (only UP and DOWN) and therefore SET_POSITION feature should be disabled for Mobilus C-ZR. Instead SET_TILT_POSITION will be enabled.

**Comment by zpieslak** [comment]
Hi @zbyhoo,

Can you please test the mentioned pull request and let me know if that works?

Thanks!

**Comment by zbyhoo** [comment]
Hi @zpieslak ,
Thanks for fast implementation. 
I've done single test and it works!
I don't want to make more to not wake up my neighbours. Will do more test tomorrow.

**Comment by zbyhoo** [comment]
@zpieslak it seems to work with one exception.
In the following situation I cannot open the cover, becase HA UI blocks it, looks like it somehow mixes position with tilt:
- move cover to close postion
- set cover tilt to 100%
- now the UI doesn't allow me to move cover to open position

![open_blocked](https://github.com/user-attachments/assets/ac5b5de9-c5a8-42b9-b084-31d0152fc48e)

When I reload the add-on, it gets back to normal.

**Comment by zpieslak** [comment]
Hi @zbyhoo,

Thanks for  your report. That might be something with dvice status returned at time when the tilt is set to 100%. Can you please check the following:

- Do the test you did above
- Right after (instantly or with small delay) when the tilt is set to 100% can you send me the device_status as done with the following command:

python -m mobilus_client --host=MOBIULS_IP --login=MOBILUS_USER --password=MOBILUS_PASSWORD current_state

Just the value that is returned in the current_state response for that particular device. I want to check what exactly is returned in the status check, maybe [this code](https://github.com/zpieslak/mobilus-client-home-assistant/blob/4c4e990e982266f40d3d6c5409e97f6e926a8da4/custom_components/mobilus/coordinator.py#L48-L52) interpret it wrong.

**Comment by zpieslak** [comment]
Hey @zbyhoo,

Thank you for your testing. It looks like the position is swap when tilt is in move. I updated the branch. Could you please check it?

**Comment by zpieslak** [comment]
Great! Thanks zbyhoo for testing. I will merge pull request and create new version then.
