### ISSUE TITLE
doesn't open shutters controlled by the mobilus C-MR module

### ISSUE THREAD

**Issue by danielkedzior** [zpieslak/mobilus-client-home-assistant#9]
Integration doesn't open roller shutters controlled by the mobilus C-MR module. 
It reads their position (open/closed), but shutters do not react after the open/close signal.

**Comment by zpieslak** [comment]
Hey @danielkedzior,

Thanks for the report. Taking your answer from the forum ([reference](https://community.home-assistant.io/t/integration-with-mobilus-gtw/473378/30)).

I may have idea how to fix it. The current implementation assumes that  shutters can receive percentage command and this is how they are controlled in HA (open is de-facto setting percentage to 100% and close to 0%). But maybe this is now always the case (as you shown in the forum). Fortunately there are also command `UP` and `DOWN` and I think this is how official app uses it.

Anyway this shouldn't be hard and I will try to fix it in spare moment.

**Comment by zpieslak** [comment]
@danielkedzior Hmm, maybe the Krispol hardware is the same as you have in C-MR, who knows :) Anyway, please check the branch in the mentioned pull request and let know if this works now for you. If so, I will merge the pull request. Thanks!

**Comment by danielkedzior** [comment]
Hi @zpieslak, I have checked, it works properly. It works with standard shutters and also with the ones controlled by C-MR. Thanks!

**Comment by zpieslak** [comment]
@danielkedzior Great! Thanks for testing. I will merge the pull request then

**Comment by Jasbi90** [comment]
Hello,
Thank you for your work on this plugin.

I also have Mobilus shutters without the percentage setting.
When I add these attributes, I don't see a slider (which I don't need).



![image](https://github.com/user-attachments/assets/a5229261-f88d-4184-8884-a6354549f963)

In the Mobilus HACS plugin, I see the following with this attribute:
![image](https://github.com/user-attachments/assets/2e643ab7-6b65-47aa-a0be-d643dc1ee2ee)
![image](https://github.com/user-attachments/assets/95fa8f7e-0940-4bc6-bb5a-616ab98e6180)


Would it be possible to implement something from the app-6a66bade0jd.js file of Mobilus?


`function() {
    "use strict";
    function e(e) {
        var t = {}
          , i = {
            1: {
                deviceName: "SENSO",
                deviceType: "updownstopslider",
                deviceDefaultIconId: 1
            },
            2: {
                deviceName: "COSMO",
                deviceType: "updownstop",
                deviceDefaultIconId: 1
            },
            3: {
                deviceName: "CMR",
                deviceType: "updownstop",
                deviceDefaultIconId: 1
            },
            4: {
                deviceName: "CGR",
                deviceType: "onebutton",
                deviceDefaultIconId: 1
            },
            5: {
                deviceName: "SWITCH",
                deviceType: "toggle",
                deviceDefaultIconId: 5
            },
            6: {
                deviceName: "SWITCH_NP",
                deviceType: "toggle",
                deviceDefaultIconId: 5
            },
            7: {
                deviceName: "COSMO_CZR",
                deviceType: "updownstopdownandslider",
                deviceDefaultIconId: 35
            },
            8: {
                deviceName: "COSMO_MZR",
                deviceType: "updownstopdownandslider",
                deviceDefaultIconId: 35
            },
            9: {
                deviceName: "SENSO_Z",
                deviceType: "updownstoptwoslider",
                deviceDefaultIconId: 35`

&

`var w = [{
            groupText: "toggle",
            permittedDeviceTypes: [5, 6]
        }, {
            groupText: "onebutton",
            permittedDeviceTypes: [4]
        }, {
            groupText: "updownstop",
            permittedDeviceTypes: [1, 2, 3, 7, 8, 9],
            moreDetailedGroups: [{
                groupText: "updownstopslider",
                permittedDeviceTypes: [1, 9],
                ancestorDevices: [2, 3, 7, 8],
                moreDetailedGroups: [{
                    groupText: "updownstoptwoslider",
                    permittedDeviceTypes: [9],
                    ancestorDevices: [1, 2, 3, 7, 8]
                }]
            }, {
                groupText: "updownstopdownandslider",
                permittedDeviceTypes: [7, 8, 9],
                isSpecialConditionsPassed: function(e) {
                    return void 0 !== e && null !== e && void 0 !== e.icon && null !== e.icon && 35 == e.icon ? !0 : !1
                },
                ancestorDevices: [1, 2, 3, 9],
                moreDetailedGroups: [{
                    groupText: "updownstoptwoslider",
                    permittedDeviceTypes: [9],
                    ancestorDevices: [1, 2, 3, 7, 8]
                }]`

It seems that setting a percentage is not possible for the COSMO and CMR devices, which only support up, down, and stop controls.

**Comment by zpieslak** [comment]
@Jasbi90 Thanks for your report! I created [a separate issue](https://github.com/zpieslak/mobilus-client-home-assistant/issues/12). Let's continue there.
